tp_mysql:
  host: 101.43.61.175
  port: 3300
  user: root
  password: zm_123456
  charset: utf8
  db: test_plat

tp_mongo:
  host: 101.43.61.175
  port: 39006
  username: "xz_test"
  password: "xz_test_pwd"
  db: autotest
  set: tp
  data_id: 622ac3b8e1d740a81de1d4f5
  info_id: 622ac1739a7636583d3fe3c3

