test_plat:
  dev:
    host: 101.43.61.175
    port: 3300
    user: root
    password: zm_123456
    charset: utf8
    db: test_plat

  pub:
    host: 101.43.61.175
    port: 3300
    user: root
    password: zm_123456
    charset: utf8
    db: test_plat