# jenkins 报告
jenkins: http://121.4.47.229:3600/job/{}/{}/allure

# 钉钉群消息机器人
ding_robot: https://oapi.dingtalk.com/robot/send?access_token=

# 企微群消息机器人
wechat_robot: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=

# 测试平台
test_plat: http://121.4.47.229:8000
